# Generated by Django 3.2.1 on 2022-08-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('DU', 'Dushanba'), ('SE', 'Seshanba'), ('CHO', 'Chorshanba'), ('PA', 'Payshanba'), ('JU', 'Juma'), ('SHA', 'Shanba')], default=1, max_length=255)),
                ('time', models.TimeField()),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.groupname')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.roomno')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.subjectname')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='page.table')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.teacher')),
            ],
        ),
    ]
