# Generated by Django 3.2.1 on 2022-08-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_fanlar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanlar',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='fanlar',
            name='week',
        ),
        migrations.RemoveField(
            model_name='table',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='table',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='table',
            name='teacher_name',
        ),
        migrations.RemoveField(
            model_name='table',
            name='time',
        ),
    ]
