# Generated by Django 3.2.1 on 2022-08-02 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20220802_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanlar',
            name='room_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.roomno'),
        ),
        migrations.AlterField(
            model_name='fanlar',
            name='subject_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.subjectname'),
        ),
        migrations.AlterField(
            model_name='fanlar',
            name='teacher_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.teacher'),
        ),
    ]
